apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: WEBHOOK_URL
              value: ""
              valueFrom: null
