apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patches:
- path: broadcaster-patch.yaml

images:
- name: PROJECT/BROADCASTER
  newName: anyasnif/broadcaster
  newTag: a1e289f96cd9217ee6ee23e3b8741c71f3668e59
- name: PROJECT/IMAGE
  newName: anyasnif/todo-app
  newTag: 5310964ee0865a24cfa76947b65dff8e26bbf297
- name: PROJECT/LOGOUTPUT
  newName: anyasnif/log-output
  newTag: 931b20c32229ebde2c6e48be4aeb36fb838a4ecb
