apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- backup-sa.yaml
- cronjob-backup.yaml

images:
- name: PROJECT/BROADCASTER
  newName: anyasnif/broadcaster
  newTag: 2d02e41497af297e77ba5fa02c715577dc5cbd13
- name: PROJECT/IMAGE
  newName: anyasnif/todo-app
  newTag: 2d02e41497af297e77ba5fa02c715577dc5cbd13
- name: PROJECT/LOGOUTPUT
  newName: anyasnif/log-output
  newTag: 2d02e41497af297e77ba5fa02c715577dc5cbd13
