apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- backup-sa.yaml
- cronjob-backup.yaml

images:
- name: PROJECT/BROADCASTER
  newName: anyasnif/broadcaster
  newTag: 80f5ec9386a7b32a7b40376f5a278c1eb6653f16
- name: PROJECT/IMAGE
  newName: anyasnif/todo-app
  newTag: 80f5ec9386a7b32a7b40376f5a278c1eb6653f16
- name: PROJECT/LOGOUTPUT
  newName: anyasnif/log-output
  newTag: 80f5ec9386a7b32a7b40376f5a278c1eb6653f16
