apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- backup-sa.yaml
- cronjob-backup.yaml

images:
- name: PROJECT/BROADCASTER
  newName: anyasnif/broadcaster
  newTag: 1db1a9fc9f0cb52d348387d04690e5acb7f015f4
- name: PROJECT/IMAGE
  newName: anyasnif/todo-app
  newTag: 1db1a9fc9f0cb52d348387d04690e5acb7f015f4
- name: PROJECT/LOGOUTPUT
  newName: anyasnif/log-output
  newTag: 1db1a9fc9f0cb52d348387d04690e5acb7f015f4
