apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  MESSAGE: "Hello from GKE"
  information.txt: |
    This file is mounted from a ConfigMap.
    Feel free to change this text and re-apply to see it update.
