apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-image-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 100Mi
